defaults: &defaults
  working_directory: ~/datastore4s
  docker:
    - image: bulbview/circleci-primary

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Compile
          command: sbt ";compile;test:compile"
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
          key: v2-dependencies-{{ checksum "build.sbt" }}
      - persist_to_workspace:
          root: .
          paths:
            - target
            - build.sbt

  unit-test:
    <<: *defaults
    steps:
      - checkout #TODO Do I need checkout??
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Unit Test
          command: sbt test

  format-check:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Scalafmt Check
          command: sbt ";scalafmtCheck;scalafmtSbtCheck"

  integration-test:
    <<: *defaults
    docker:
      - image: bulbview/circleci-primary
      - image: xaviiic/alpine-cloud-datastore-emulator:1.2.1
        entrypoint: ["gcloud", "beta", "emulators", "datastore", "start", "--project=datastore4s-project", "--no-store-on-disk", "--host-port=localhost:8380"]
    environment:
      - DATASTORE_PROJECT_ID: datastore4s
      - DATASTORE_HOST: http://localhost:8380
      - DATASTORE_EMULATOR_HOST: http://localhost:8380
      - DATASTORE_EMULATOR_HOST_PATH: localhost:8380/datastore
      - DATASTORE_DATASET: datastore4s
    steps:
      - checkout #TODO Do I need checkout??
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Integration Test
          command: sbt it:test

  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Extract Bintray Creds
          command: build/bintray.sh
      - run:
          name: Publish
          command: sbt publish


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - build
      - format-check
      - publish:
          requires:
            - unit-test
            - integration-test
            - format-check
          filters:
            branches:
              only:
                - master
