defaults: &defaults
  working_directory: ~/datastore4s
  docker:
    - image: bulbview/circleci-primary

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Compile
          command: sbt ";compile;test:compile"
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
          key: v2-dependencies-{{ checksum "build.sbt" }}
      - persist_to_workspace:
          root: .
          paths:
            - target
            - build.sbt

  unit-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Unit Test
          command: sbt test

  format-check:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Scalafmt Check
          command: sbt ";scalafmtCheck;scalafmtSbtCheck"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - format-check